# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5eca07df3bdd3207199441283c9bef94a0f6a89aaa91c58988389e43586fbdd60360268bf070af32a7b680d011efbe2c24ce9187c48f9955bcf67eef438602e

test:
  secret_key_base: 45c576c787f971991e6d6884cbccba6f1cd4d8513483ff1e1e5e7bed0d1ef585467237f16e4127a6fa4ed35c668838285ae071ae8ed2359d7ba647856e1ca889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
